name: 'material_icons_named'
description: 'A mapping library that maps the Stringified material icon name to the actual Material `IconData`.'
homepage: 'https://github.com/peiffer-innovations/material_icons_named'
version: '3.7.0'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: 'flutter'

dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  http: ">=0.13.5 <2.0.0"

flutter:
  uses-material-design: true

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
