// ignore_for_file: avoid_print

import 'dart:io';

import 'package:http/http.dart' as http;

Future<void> main(List<String> args) async {
  final response = await http.get(
    Uri.parse(
      'https://raw.githubusercontent.com/flutter/flutter/master/packages/flutter/lib/src/material/icons.dart',
    ),
  );

  var body = response.body;
  body = body.substring(
    body.indexOf('// BEGIN GENERATED ICONS'),
    body.indexOf('// END GENERATED ICONS'),
  );

  final lines = body.split('\n');

  final regex = RegExp(r'IconData (?<icon>\S*)');

  final file = File('lib/material_icons_named.dart');
  var data = '''
// AUTOGENERATED FILE; DO NOT EDIT

import 'package:flutter/material.dart';

const materialIcons = {
''';

  final icons = <String>[];
  for (var line in lines) {
    if (regex.hasMatch(line)) {
      final match = regex.firstMatch(line)!;

      final icon = match.namedGroup('icon')!;

      print(icon);

      icons.add(icon);
    }
  }

  icons.sort();
  for (var icon in icons) {
    data += "'$icon': Icons.$icon,\n";
  }

  data += '\n};';

  if (file.existsSync()) {
    file.deleteSync(recursive: true);
  }
  file.createSync(recursive: true);
  file.writeAsStringSync(data);

  print('');
  print('Generated: ${file.absolute.path}');
  print('Formatting...');
  Process.runSync('dart', ['format', 'lib']);

  print('');
  print('DONE!');
}
