// ignore_for_file: avoid_print

import 'dart:io';

import 'package:http/http.dart' as http;

Future<void> main(List<String> args) async {
  var response = await http.get(
    Uri.parse(
      'https://raw.githubusercontent.com/flutter/flutter/beta/packages/flutter/lib/src/material/icons.dart',
    ),
  );

  var body = response.body;
  body = body.substring(
    body.indexOf('// BEGIN GENERATED ICONS'),
    body.indexOf('// END GENERATED ICONS'),
  );

  var lines = body.split('\n');

  var regex = RegExp(r'IconData (?<icon>\S*)');

  var file = File('lib/material_icons_named.dart');
  var data = '''
// AUTOGENERATED FILE; DO NOT EDIT

import 'package:flutter/material.dart';

const materialIcons = {
''';

  var icons = <String>[];
  for (var line in lines) {
    if (regex.hasMatch(line)) {
      var match = regex.firstMatch(line)!;

      var icon = match.namedGroup('icon')!;

      print(icon);

      icons.add(icon);
    }
  }

  icons.sort();
  for (var icon in icons) {
    data += "'$icon': Icons.$icon,\n";
  }

  data += '\n};';

  if (file.existsSync()) {
    file.deleteSync(recursive: true);
  }
  file.createSync(recursive: true);
  file.writeAsStringSync(data);

  print('');
  print('Generated: ${file.absolute.path}');
  print('Formatting...');
  await Process.runSync('dart', ['format', 'lib']);

  print('');
  print('DONE!');
}
